### ISSUE TITLE
Issue when module directory name contains dash(es)

### ISSUE THREAD

**Issue by nvisionative** [mtrutledge/generator-dnn#18]
There is an issue when the module directory name contains a dash or dashes.

![screencapture_ 2018-07-03 05 28 pm _1720](https://user-images.githubusercontent.com/4568451/42245370-8c95c690-7ee6-11e8-99c2-17c2f238bf1c.png)

The workaround is to remove all dashes from the module directory name.  It doesn't seem to matter if the parent directory for the module contains a dash or dashes.

![screencapture_ 2018-07-03 05 30 pm _1721](https://user-images.githubusercontent.com/4568451/42245461-ed5c5bec-7ee6-11e8-8db4-b89e9a5a8c02.png)
![screencapture_ 2018-07-03 05 31 pm _1722](https://user-images.githubusercontent.com/4568451/42245467-f220ccf8-7ee6-11e8-997f-c15d29c14591.png)

**Comment by mtrutledge** [comment]
Thanks for reporting this David. I will take a look. Have a happy 4th of July!

Matt

**Comment by mtrutledge** [comment]
I have a fix for this I am testing. Should have a new release soon.

**Comment by nvisionative** [comment]
Excellent - thanks @mtrutledge !

**Comment by ahoefling** [comment]
@mtrutledge I was creating a new module today and noticed the same behavior for spaces. You may want to add that to your test case if you haven't already

**Comment by mtrutledge** [comment]
I haven’t had a issue with the spaces only before. I will double check before I push this fix up to make sure.

**Comment by mtrutledge** [comment]
This has been resolved in version 1.0.7 which will be published shortly.
