### ISSUE TITLE
Issue when the module name contains dash(es)

### ISSUE THREAD

**Issue by nvisionative** [mtrutledge/generator-dnn#19]
There is an issue with the module name contains a dash or dashes.  The current workaround is to not use dashes in the module name.

![screencapture_ 2018-07-03 05 40 pm _1723](https://user-images.githubusercontent.com/4568451/42245840-44f52572-7ee8-11e8-822c-d7ef16905d6a.png)

**Comment by mtrutledge** [comment]
I have a fix for this I am testing. Should have a new release soon.

**Comment by nvisionative** [comment]
Excellent - thanks @mtrutledge !

**Comment by mtrutledge** [comment]
This has been resolved in version 1.0.7 which will be published shortly.
