### ISSUE TITLE
[MVC] Settings.resx is not being generated correctly

### ISSUE THREAD

**Issue by ahoefling** [mtrutledge/generator-dnn#26]
When generating a MVC project the Settings.resx file is not being generated correctly the file is malformed and won't open in Visual Studio:

![image](https://user-images.githubusercontent.com/17751436/42919516-559de13a-8ae0-11e8-893d-38dd269ccdd8.png)

After further investigation it appears that the following fields contain <%= moduleName %> which appears to be correct generator syntax as a placeholder

+ BasicSettings.Text
+ ControlTitle_settings.Text

My assumption is the xml is not being properly parsed in this case. I took a look at the SPA configuration and it doesn't have these fields so we could just rip it out.

@mtrutledge what direction would you like to go with this?

**Comment by mtrutledge** [comment]
I noticed this earlier today and ripped it out on my local machine. I have some more tests to do before committing but this should be fixed when I push my next code.

**Comment by mtrutledge** [comment]
I added a MVC and SPA label so we can label the issues.

**Comment by mtrutledge** [comment]
This has been resolved
