### ISSUE TITLE
Ability to add modules to an existing solution

### ISSUE THREAD

**Issue by sholman** [mtrutledge/generator-dnn#44]
## Describe the solution you'd like
It would be good to be able to run dnn-generator within an existing solution folder and it to default to (or ask) adding the new module project to the existing solution.

## Additional context
Currently, it seems to notice the conflict adding the file and ask if you'd like to overwrite your .sln file. If you say No, it creates the module project, and you can add it to the solution manually.

**Comment by mtrutledge** [comment]
Actually if you say yes it keeps the solution file and adds the project without losing the existing projects.

**Comment by mtrutledge** [comment]
This is a limitation of the men fs file system yeoman uses. It will not allow a file to be altered without permission from the user.
