### ISSUE TITLE
Add GitHub Topics to repo

### ISSUE THREAD

**Issue by nvisionative** [mtrutledge/generator-dnn#52]
## Please summarize your question in one sentence
For optimum discoverability, you'll need to add topics for **dnn**, **dnncms**, **dotnetnuke** at minimum.

## Give a more extended description
GitHub Topics are added to repos by clicking **Manage Topics** just below the repo **Description**.

**Comment by mtrutledge** [comment]
These have been added to the repos topics. Thanks David!
