### ISSUE TITLE
Update repo Description and README to use optimum keywords

### ISSUE THREAD

**Issue by nvisionative** [mtrutledge/generator-dnn#53]
## Please summarize your question in one sentence
For optimum discoverability, you'll need to update the repo's Description to include **DNN** and **DotNetNuke** keywords at minimum.

## Give a more extended description
A common practice is to use **DNN (formerly DotNetNuke)** within the **Description** and **README**.

**Comment by mtrutledge** [comment]
I have added DotNetNuke to the description of the Readme file on the development branch. It will be merged back to master and released with version 1.0.8
